[project]
name = "sprk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fddemarco", email = "franco.demarco3400@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyspark[pipelines]>=4.2.0",
]

[project.scripts]
sprk = "sprk:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
